steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE_URI}
      - --build-arg
      - OPENCLAW_VERSION=${_OPENCLAW_VERSION}
      - .

images:
  - ${_IMAGE_URI}

substitutions:
  _OPENCLAW_VERSION: "2026.4.21"
